spring.application.name=Pern-Merch-Website
# Server
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/pern-merch
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# change to update to keep tables after runs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000