spring.application.name=Pern-Merch-Website
# Server
server.port=8080

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# change to update to keep tables after runs
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

admin.secret.username=${ADMIN_USERNAME}
admin.secret.password=${ADMIN_PASSWORD}

# set to dev environment, which activates the dataSeeder
spring.profiles.active=dev
